### ISSUE TITLE
Regarding the issue of zone_spec.json

### ISSUE THREAD

**Issue by whutGuoao** [uwgraphics/ProximityPlanarRecovery#1]
Hello, I am very interested in this project. What information is in the zone_spec.json file? Is it the array size of tmf8820？

**Comment by cpsiff** [comment]
Sorry for the delay, I wasn't notified of this for some reason.

zone_spec.json describes the field-of-view of each of the 9 "zones" in the TMF8820, which is why there are 9 items in the main array. For each zone, it contains:

center: the angular x and y position of the center of the zone, in radians
width: the angular field of view of the zone in the x direction, in radians
height: the angular field of view of the zone in the y direction, in radians

To convert an angular coordinate into a unit vector pointing in the given direction, use this function: https://github.com/uwgraphics/ProximityPlanarRecovery/blob/e8c22d1754edeca12a59c5b54451093a399457e2/util.py#L31

the _px fields describe the pixel position of the zones, following the convention on page 23 of [the datasheet](https://look.ams-osram.com/m/52236c476132a095/original/TMF8820-21-28-Multizone-Time-of-Flight-Sensor.pdf). I have a script elsewhere that uses the formula on the same page to derive the angular coordinates from the pixel positions.

**Comment by cpsiff** [comment]
Feel free to comment or reach out if you have other questions.

**Comment by whutGuoao** [comment]
> Feel free to comment or reach out if you have other questions.

Thank you very much for your answer. I have understood the meaning of the parameters in zone_spec.json. After reading your paper, I am very interested in the direct_method. Is the 'center' parameter in zone_spec iterated from the collected dataset or calculated through a formula?

**Comment by cpsiff** [comment]
The "center" parameter comes straight from page 23 of the datasheet. For the direct method, we tweak the center location by optimizing over some large dataset (this is described in the paper). You can see in the direct method demo code where we multiply the center location by a factor before using it: https://github.com/uwgraphics/ProximityPlanarRecovery/blob/e8c22d1754edeca12a59c5b54451093a399457e2/direct_method.py#L24 There is a different factor for zones on the edge vs on the corner.

**Comment by whutGuoao** [comment]
sorry, I have another question about the 'center' parameter. Are the values of x and y angular positions FOV/3 for TMF8820? For example, 33 °/3 and 32 °/3. Is it the same for tmf8821? For example, as shown in the figure, it is 41 °/4 and 52 °/4.

![Image](https://github.com/user-attachments/assets/3965a0d2-f42a-49e5-8f9d-de16fefdcef8)

**Comment by cpsiff** [comment]
The values aren't quite as simple as the full FoV divided by the number of (rows/columns), because the different zones have different shapes, as you can see in the figure you posted. For example Zone 1 is 5x3 pixels while zone 6 is 4x2 pixels.

So for the zone map you sent, you'll need to manually enter in the centerpoint of each zone. Treat one pixel (green square) as one unit, and the optical axis (red circle) as 0,0). For example, zone 1 has a centerpoint of (-6.5, -3.5), a width of 5, and a height of 3.

The "center", "width", and "height" parameters are derived from those pixel coordinates using the formula around that same page on the datasheet. Here's a script that does it for you. Just replace CPS and SIZES with the appropriate values for the spad map you want to use. If you're doing 4x4 you'll have to modify the part where I rotate the zones by 180 about the optical axis as well.

```python
"""
Given the centerpoints, widths, and heights of each SPAD zone in spad pixel coordinates, create a 
zone_spec.json file, which specifies the center, width, and height of each SPAD zone in angular
coordinates.
"""

import json
import matplotlib.pyplot as plt
import numpy as np

# These numbers come from page 23 of the TMF882X user manual, and are used to calculate the FoV of a
# set of SPADs (https://ams.com/documents/20143/6015057/TMF882X_DS000693_5-00.pdf)
FOCAL_DIST = 400
SPAD_SIZE_X = 16.8
SPAD_SIZE_Y = 38.8

# the below CPS and SIZES are for zone spec 1
CPS = [ 
    [-4.5,2 ], [0,2 ], [4.5,2 ],
    [-4.5,0 ], [0,0 ], [4.5,0 ],
    [-4.5,-2], [0,-2], [4.5,-2]
]
# width and height of each zone in SPAD pixels for 3x3 Normal mode (spad_map_id=1)
SIZES = [
    [5, 2], [4, 2], [5, 2],
    [5, 2], [4, 2], [5, 2],
    [5, 2], [4, 2], [5, 2],    
]

# All the zones are actually rotated about 180 degrees about the optical (z axis).
# This fixes that.
# 6 3 0       2 5 8
# 7 4 1       1 4 7
# 8 5 2       0 3 6
new_indexes = [2, 5, 8, 1, 4, 7, 0, 3, 6]
REARRANGED_CPS = [CPS[i] for i in new_indexes]
REARRANGED_SIZES = [SIZES[i] for i in new_indexes]

def TMF882X_SPAD_coord_to_angle(x, y):
    """
    Convert some "coordinate" in the TMF882X SPAD map to the angle of a ray which corresponds to
    that point on the SPAD map, relative to the optical axis of the camera (which corresponds to 
    coordinate (0,0).)

    Args:
        x, y: "coordinate" in SPAD map as viewed on page 23 of the user manual. The optical center,
          in the center of the SPAD array, corresponds to an input of (0,0) to this function. The
          positive x axis goes to the right in the diagram, and the y axis goes up. 

          For example, for spad_map_id = 1, the furthest-from-the-center corner of zone 1 would
          correspond to a coordinate of (-7, 3).
    
    Returns:
        angle_x, angle_y: angle, relative to the optical axis, of a vector pointing in the direction
          of the FoV of the given SPAD coordinate, in radians.
    """
    angle_x = 2*np.arctan((x*SPAD_SIZE_X)/(2*FOCAL_DIST))
    angle_y = 2*np.arctan((y*SPAD_SIZE_Y)/(2*FOCAL_DIST))

    return(angle_x, angle_y)

def main():
    zone_spec = []
    zone_corners = []
    for cp, size in zip(REARRANGED_CPS, REARRANGED_SIZES):
        zone_spec.append(
            {
                "center": TMF882X_SPAD_coord_to_angle(*cp),
                "width": TMF882X_SPAD_coord_to_angle(size[0], 0)[0],
                "height": TMF882X_SPAD_coord_to_angle(0, size[1])[1],
                "center_px": cp,
                "width_px": size[0],
                "height_px": size[1]
            }
        )
        zone_corners += [
            [cp[0] - size[0]/2, cp[1] - size[1]/2],
            [cp[0] + size[0]/2, cp[1] - size[1]/2],
            [cp[0] + size[0]/2, cp[1] + size[1]/2],
            [cp[0] - size[0]/2, cp[1] + size[1]/2]
        ]

    with open("map_6.json", "w+") as f:
        json.dump(zone_spec, f, indent=3)

    fig, ax = plt.subplots()
    ax.scatter([x[0] for x in zone_corners], [x[1] for x in zone_corners])
    ax.set_aspect('equal')
    # set x and y ticks to be at every integer
    ax.set_xticks(np.arange(-10, 10, 1))
    ax.set_yticks(np.arange(-10, 10, 1))
    ax.grid(which='major', axis='both')
    plt.show()

if __name__ == "__main__":
    main()
```
